### ISSUE TITLE
Some question about installation

### ISSUE THREAD

**Issue by zhoufy20** [GiftBTE-developer/GiftBTE#10]
Dear developers of GiftBTE:

I follow the document to install the useful tools step by step, but there is a question about running `make` code. 

Your response and assistance in this matter would be greatly appreciated.  

Sincerely,

Feiyu Zhou

![image](https://github.com/GiftBTE-developer/GiftBTE/assets/114725470/4c6f67ff-a201-4e24-bb4a-8465bffde1bc)

**Comment by RemusSh** [comment]
Hi Feiyu,

It seems that you are using the Intel compilers to compile the code. Actually, we recommend using gcc instead. Firstly, please type the command ```g++ -v``` to ensure that gcc has been installed in your environment. After confirming the installation, you can set the environment variable to use gcc for compiling GiftBTE. Hope it will work : )

**Comment by zhoufy20** [comment]
Dear RemusSh:

Thanks for your assistance! I changed the Intel compilers, and it successfully worked.

Sincerely,

Feiyu.
