### ISSUE TITLE
My own material data cannot be used.

### ISSUE THREAD

**Issue by hanyka** [GiftBTE-developer/GiftBTE#7]
I use phonon scattering data from five 2D materials. The GiftBTE  cannot work.

terminate called after throwing an instance of 'std::invalid_argument'
what(): stod
APPLICATION TERMINATED WITH THE EXIT STRING; Aborted (signal 6)

**Comment by Tago1** [comment]
I also met with this error when using my own ShengBTE files of one 3D material:
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stod
[cb07:21525] *** Process received signal *** 
[cb07:21525] Signal: Aborted (6) 
[cb07:21525] Signal code:  (-6)

**Comment by JoshuaXu7** [comment]
Please try the latest version.
